version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  postgres-master1:
    image: postgres:13
    environment:
      POSTGRES_USER: master1
      POSTGRES_PASSWORD: master1pass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - ./master1-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-master1.conf:/usr/share/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/usr/share/postgresql/postgresql.conf"]

  postgres-master2:
    image: postgres:13
    environment:
      POSTGRES_USER: master2
      POSTGRES_PASSWORD: master2pass
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - ./master2-init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-master2.conf:/usr/share/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/usr/share/postgresql/postgresql.conf"]

  debezium:
    image: debezium/connect:latest
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium-connect-configs
      OFFSET_STORAGE_TOPIC: debezium-connect-offsets
      STATUS_STORAGE_TOPIC: debezium-connect-status
    ports:
      - "8083:8083"
    depends_on:
      - kafka
      - postgres-master1
      - postgres-master2
